server:
  port: 9090

aws:
  s3:
    bucket:
      name: voyager-excel-files-bucket
  region: ap-south-1
  accessKeyId: AKIAZ2JHZUL7WWKGVGB2
  secretKey: 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



file:
  path: "C:\\Users\\bajir\\Downloads\\Org_Emp_Details.xlsx"


